### ISSUE TITLE
フロントエンドの子ども一覧をソートしてからリクエストする

### ISSUE THREAD

**Issue by Syuparn** [project-inclusive/OpenFisca-Japan#104]
制度によっては、第一子のみ適用額が異なる等きょうだいの年齢順が重要になるものがあります。
Openfiscaでは設計上世帯員の年齢ソート、抽出を同時に行うのが複雑なため、フロントエンドの時点で年齢順に並べているとバックエンド実装負荷を下げることが期待できます。

**Comment by Syuparn** [comment]
こちら実装可能性の調査から行おうと思います。

**Comment by SnoozingJellyfish** [comment]
役割的にはOpenFiscaで第一子、第二子…が判定できた方が良いような気もします。
`openfisca_japan/variables/福祉/育児/児童手当.py`では`np.argsort(年齢)`でソートしているのですが、対応難しそうでしょうか？

**Comment by Syuparn** [comment]
@SnoozingJellyfish (cc: @he23inw3)

issue起票時は、以下のケースで `np.argsort(年齢)` を使うと添え字がずれてしまい期待した値を取れないことを懸念していました。

```py
学年一覧 = 対象世帯.members("学年", 対象期間)
子供である = 対象世帯.has_role(世帯.子)

子どもの学年一覧 = 学年一覧[子どもである]
高校生一覧 = 子どもの学年一覧[子どもの学年一覧 >= 10 & 子どもの学年一覧 <= 12]
# 年齢順にソート
子どもの学年の降順インデックス = np.argsort(子どもの学年一覧)
# len(高校生一覧) != len(子どもの学年の降順インデックス) なので添え字がずれてしまい想定通り参照できない？
```

ですが、改めて考えると額が異なるのは「一人目の高校生」ではなく「第一子」なので、以下のように取得できることに気づきました。

```py
# ...
第一子の学年 = 子どもの学年一覧[子どもの学年の降順インデックス[0]]
if 第一子の学年 >= 10 and 第一子の学年 <= 12:
	第一子の高校種別 = 高校種別一覧[子どもの学年の降順インデックス[0]]
	# 第一子の額追加...

# 第二子以降も同様の方法で取得
```

**Comment by SnoozingJellyfish** [comment]
PR #105 で対応済みのためクローズします。
