### ISSUE TITLE
生活保護費算出時に、世帯数が5人よりも多いと異常終了する

### ISSUE THREAD

**Issue by he23inw3** [project-inclusive/OpenFisca-Japan#111]
生活保護費算出では、世帯数をキーとしてCSVから該当値を取得する。https://github.com/project-inclusive/OpenFisca-Japan/blob/d8a127744c99c6f009e2aed6c4b7d2277243bace/openfisca_japan/variables/%E7%A6%8F%E7%A5%89/%E7%94%9F%E6%B4%BB%E4%BF%9D%E8%AD%B7.py#L479-L481
世帯数が5人よりも多い場合、CSVには該当値がないため、そのまま検索するとKeyErrorとなり異常終了する。
<img width="180" alt="image" src="https://github.com/project-inclusive/OpenFisca-Japan/assets/27355202/e0218e3d-833a-4de5-974f-a32e31aa612d">

```
/home/user/.local/lib/python3.8/site-packages/openfisca_japan/variables/福祉/生活保護.py:480: KeyError
================================ short test summary info =================================
FAILED openfisca_japan/tests/東京都/福祉/高等学校奨学給付金.yaml:: - KeyError: '7人'
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! stopping after 1 failures !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
============================== 1 failed, 18 passed in 1.17s ==============================
```

類似の処理を行っているところも同様の事象が発生すると思われるので、横展開の調査から始めたほうが良いと思います。

**Comment by he23inw3** [comment]
生活保護しか確認していないが、世帯人数の上限を超えると上限値と同一として扱う実装となっている。
生活扶助本体に係る経過的加算だけが処理を入れていないみたいなので、同じ処理を追加しテストを実施した。
念のためその他の加算で同様のロジックを行っている加算についてもテストを追加・実施した。

https://github.com/project-inclusive/OpenFisca-Japan/pull/114

**Comment by SnoozingJellyfish** [comment]
#114 で対処済みのためクローズします。
