### ISSUE TITLE
結果画面に遷移した時にチャットボット領域まで勝手にスクロールされる (When transitioning to the results page, the page is automatically scrolled to chatbot iframe.)

### ISSUE THREAD

**Issue by SnoozingJellyfish** [project-inclusive/OpenFisca-Japan#122]
結果画面に遷移した時、下部のチャットボットが起動したタイミングで、ページが勝手にチャットボット領域までスクロールされます。
上部の算出金額を十分確認する前に勝手にスクロールされるため、そうならないようにする必要があります。
（PCのChrome, Edgeブラウザで発生します。PCのsafari, スマホのchromeでは発生しません。firefox, スマホのsafariでは未確認です。）

When transitioning to the results page, the page automatically scrolls to the chatbot iframe when the chatbot at the bottom starts.
This will automatically scroll before users fully check the calculated amount at the top, so it's necessary to prevent this from happening.
(It occurs in Chrome and Edge browsers on PCs. It does not occur in safari on PCs and chrome on smartphones. It has not been confirmed on firefox and safari on smartphones.)

**Comment by Syuparn** [comment]
チャットボットのiframeを別のhtmlに埋め込んだ場合もスクロールが発生したため、チャットボット内部のscriptによるものと思われます。

I suspect it is caused by scripts inside the chatbot website because another html embedding the iframe is also auto-scrolled.

(Windows/Chrome)

**Comment by SnoozingJellyfish** [comment]
情報ありがとうございます！　チャットボット内部のscriptに手を入れられるか分かりませんが、仕様や設定の開発ドキュメントができたら確認してみたいですね。

Thank you for the information! I don't know if we can modify the script inside the chatbot, but we'd like to check it out once the development document for specifications and settings is ready.

**Comment by SnoozingJellyfish** [comment]
勝手にスクロールされないようにするのが難しければ、iframeによる表示をなくし、Miboページに遷移するボタンを置いても良いかもしれません。

If it is difficult to prevent the page from being scrolled by itself, it may be OK to eliminate iframe and place a link button to the Mibo page.

**Comment by SnoozingJellyfish** [comment]
fixed by commit e0f90d7ac7327c22c70fe29e2ae050cb13aa0481 .
(waiting 5 second until displaying chatbot)
