### ISSUE TITLE
高等学校奨学給付金の私立高校の場合の実装

### ISSUE THREAD

**Issue by SnoozingJellyfish** [project-inclusive/OpenFisca-Japan#126]
[国のHP](https://www.mext.go.jp/a_menu/shotou/mushouka/1344089.htm)では公立・私立によって支給額が異なり、私立の場合が実装できていません。
[東京都のHP](https://www.kyoiku.metro.tokyo.lg.jp/admission/tuition/tuition/scholarship_public_school.html)では公立の場合のみ記載されていました。
高等学校奨学給付金では国立と公立は同じ扱いですが、今後他の制度を実装する際に区別する必要が出てくるかもしれないので、国立・公立・私立と分けて定義をお願いします。

- [x] 私立の場合の支給額を算出するようにOpenFiscaバックエンドのvariableを修正・テスト
- [x] フロントエンドの高校種別に国立・公立・私立の選択肢を追加

**Comment by SnoozingJellyfish** [comment]
PR #129 でバックエンド実装が完了しました。

**Comment by he23inw3** [comment]
本件FE側実施される方がいらっしゃらければ、私実施しようかと思いますがいかがいたしましょうか？
担当いらっしゃる場合は譲りまする。

仕事でvue2系を少し触ったのみなので時間かかるかもですが。。

**Comment by SnoozingJellyfish** [comment]
@he23inw3 
ぜひお願いします！
Highschool.tsxの中に高校運営種別を追加して、高校履修種別の横に置く感じがいいかなと思います。
コンボボックスを横に並べる方法は、PrefectureMunicipality.tsxを参考にしてください。

**Comment by he23inw3** [comment]
@SnoozingJellyfish 
承知しました。
以下のように実装しましたが、イメージ合いそうでしょうか？

![image](https://github.com/project-inclusive/OpenFisca-Japan/assets/27355202/8b2a7d4c-c458-4c3c-832d-47a8d6b4c8ed)

**Comment by SnoozingJellyfish** [comment]
@he23inw3 
はい、そのようなイメージです！
ちなみに、console.logでPOST前後のhouseholdを出力しており、ブラウザのデベロッパー画面で確認できます。
「高校に通っている」のチェックボックスを外したときにhouseholdの高校種別が「無」になっているか等、ご確認いただけると助かります。

**Comment by he23inw3** [comment]
@SnoozingJellyfish 
上記のチェックを外した時に「無」となっていることを確認しました。

![image](https://github.com/project-inclusive/OpenFisca-Japan/assets/27355202/70a26423-6417-49c2-afdd-884e2f2e5b19)
![image](https://github.com/project-inclusive/OpenFisca-Japan/assets/27355202/af966621-b2ea-49be-b760-aeb8b0e37657)
![image](https://github.com/project-inclusive/OpenFisca-Japan/assets/27355202/97826868-b6e1-495b-baa7-9d9c18223050)

チェックをつけて入力し給付金欄に値出るかも確認しておきました。
* 子供一人パターン_入力値デフォルトパターン
![image](https://github.com/project-inclusive/OpenFisca-Japan/assets/27355202/aa081229-dae4-4960-b41d-9d8a3a0524dc)
![image](https://github.com/project-inclusive/OpenFisca-Japan/assets/27355202/ec8a0cc2-8c93-4cac-9b9d-c0880e3ae79b)

* 子供一人パターン_入力値デフォルトから変更パターン
![image](https://github.com/project-inclusive/OpenFisca-Japan/assets/27355202/880d3838-de35-43a3-86b7-dc975cc17aab)
![image](https://github.com/project-inclusive/OpenFisca-Japan/assets/27355202/4f7750ea-0a7d-487c-a31a-e9009430fc94)

* 子供複数人パターン_デフォルトのまま
![image](https://github.com/project-inclusive/OpenFisca-Japan/assets/27355202/52599b49-3ec6-4dbd-a624-3628ac24deb4)
![image](https://github.com/project-inclusive/OpenFisca-Japan/assets/27355202/049190f4-15a7-4a1d-9824-70d10beffc08)

* 子供複数人パターン_デフォルトから変更
![image](https://github.com/project-inclusive/OpenFisca-Japan/assets/27355202/df3dcdd4-d726-495a-9753-e9646acd1bfb)
![image](https://github.com/project-inclusive/OpenFisca-Japan/assets/27355202/70fc06ce-ca3e-46ff-b86a-7a47eef067e2)

こちらは別件ですが、多分Form内のID重複? と SameSite(対象はmiibo？)関連のissue が出ていました。
<img width="432" alt="image" src="https://github.com/project-inclusive/OpenFisca-Japan/assets/27355202/42ffd4f2-c11f-475a-aa3b-5972d6295304">

**Comment by SnoozingJellyfish** [comment]
@he23inw3 
確認ありがとうございます！期待する動きをしていそうですね。

devtoolのissueについては、Edgeブラウザに表示されていますでしょうか？ Chromeでは表示されないので気づいていませんでした。
idは明示的には指定しておらず、ReactがよしなにIDを振っているのかと思っていました、、、
手元でEdgeブラウザがないのですが、「Duplicate for field id in the same form」の詳細は何が記載されていますでしょうか？

miibo関連はChromeでもエラーが出ており、何らかの対処をするつもりなので無視していただいて構いません。

**Comment by he23inw3** [comment]
@SnoozingJellyfish 
承知しました。
こちらの件は、この後PRを出すようにします。
issueは、Google Chrome(バージョン: 116.0.5845.188（Official Build） )で確認しました。
ID重複の詳細はこちらです。
![image](https://github.com/project-inclusive/OpenFisca-Japan/assets/27355202/eb73d77e-b9d7-46b9-a7fa-3519fc8672c7)

**Comment by SnoozingJellyfish** [comment]
@he23inw3 
Chromeでissue出せるんですね。
私もフロントエンドに詳しくないのでどう対処すれば良いかわからないですが、現時点でauto fill はしないので、一旦そのままにしておきましょうか。。

**Comment by SnoozingJellyfish** [comment]
PR #131 で対応したためクローズします。
