### ISSUE TITLE
PR作成時に自動でテストが実行されるようにする

### ISSUE THREAD

**Issue by Syuparn** [project-inclusive/OpenFisca-Japan#128]
修正によって別の既存の実装が意図せず仕様を満たさなくなってしまうのを防ぐため、PR作成時にテストを自動実行します。
テストを実行するGitHub Actionを作成します。

流すテスト候補

- `make test` (バックエンド)
- `npm run cy:run` (フロントエンド)

**Comment by SnoozingJellyfish** [comment]
イシュー作成ありがとうございます！
github actionで`make test`を行う方法は[過去の実装跡](https://github.com/SnoozingJellyfish/OpenFisca-Yuisekin/blob/main/.github/workflows/workflow.yml) が参考になるかもしれません。

**Comment by Syuparn** [comment]
情報ありがとうございます！draft PRで動作確認しながら作っていきたいと思います。

**Comment by SnoozingJellyfish** [comment]
PR #130 で対応のためクローズ
