### ISSUE TITLE
高等学校等就学支援金制度のフロントエンド作成

### ISSUE THREAD

**Issue by Syuparn** [project-inclusive/OpenFisca-Japan#133]
[Figma](https://www.figma.com/file/izSZUKF9r19BwkEnUZhHrM/%E3%83%9E%E3%82%A4%E5%88%B6%E5%BA%A6%E3%82%B7%E3%83%9F%E3%83%A5%E3%83%AC%E3%83%BC%E3%82%BF%E3%83%BC?type=design&node-id=0%3A1&mode=design&t=ArZGglM6HWTQMfIt-1)のフォーム画面・結果画面のGUIをもとに、高等学校等就学支援金のフロントエンドを作ります。

「給付されるお金」に「児童手当」と同様に「高等学校等就学支援金」のプルダウンを作成します。
結果画面の説明に以下の文言を記載します。
「高校の授業料の支援金。本人が直接受け取る代わりに、授業料が減額されます。」.
「詳細リンク」のリンク先は https://www.mext.go.jp/a_menu/shotou/mushouka/1342674.htm としてください。

(より良い文言が思いついた場合はそちらを使用していただいて構いません)

**Comment by Syuparn** [comment]
`本人が直接受け取る代わりに、授業料が減額されます` についてはこちらの記述をもとにしました

https://www.mext.go.jp/a_menu/shotou/mushouka/1342600.htm
> Q　就学支援金は誰が受け取るのですか？ 
> A　学校設置者（都道府県や学校法人など）が、生徒本人に代わって受け取り、授業料に充てることになります。生徒本人（保護者）が直接受けとるものではありません。

**Comment by Syuparn** [comment]
#134 完了後に着手可能

**Comment by SnoozingJellyfish** [comment]
以下やることです。

- [ ] `dashboard/src/config/app_config.json`の `"result": {"給付制度": {"制度一覧": {...}}}` に以下のキーとバリューを追加します。  
```
"高等学校等就学支援金": {
    "unit": "円/月",
    "caption": ["高校の授業料の支援金。本人が直接受け取る代わりに、授業料が減額されます。"],
    "reference": "https://www.mext.go.jp/a_menu/shotou/mushouka/1342674.htm"
},
```

- [ ] `dashboard/src/state.ts` の `householdAtom` に `高等学校等就学支援金_最大`と`高等学校等就学支援金_最小`を追加します。
- [ ] リポジトリルートのREADME.md の `概要`に「高等学校等就学支援金」を追加します。
- [ ] `docker compose up`でブラウザにプレビューされる画面で、以下の手順で高等学校等就学支援金の見積もり結果が表示されることを確認します。
  - 「くわしく見積もり」ボタンを押す。
  - 「子どもがいる」にチェックを入れて「子供の人数」を1人にする。
  - 子供の生年月日を2008年1月1日等の高校生相当になるように入力
  - 「給付される可能性のある制度」の欄に高等学校等就学支援金の説明と参照リンクが表示されること。

**Comment by minagishl** [comment]
こちら着手させていただきます

**Comment by SnoozingJellyfish** [comment]
#251 で対応したためクローズします
