### ISSUE TITLE
高等学校等就学支援金制度のバックエンド実装（専攻科以外）

### ISSUE THREAD

**Issue by Syuparn** [project-inclusive/OpenFisca-Japan#136]
高等学校等就学支援金の算出ロジックを、バックエンドのOpenFisca Python APIで実装・テストします。
単体テストのパターン網羅は別のissueで対応するため、このissueでは最小限のテストで構いません。

- 条件 https://www.mext.go.jp/a_menu/shotou/mushouka/1342674.htm
	- 加算額の条件 https://www.mext.go.jp/a_menu/shotou/mushouka/20220329-mxt_kouhou02-3.pdf
- 金額
  - https://www.mext.go.jp/a_menu/shotou/mushouka/__icsFiles/afieldfile/2020/04/30/100014428_4.pdf

実装方法

- #134 の仮実装に実際の計算式を実装
- Variableの作成方法は openfisca_japan/variables/福祉/生活保護.py が参考になりそう
- 単位制か否かで金額が変わるため、額に幅を持たせられるようにする(Variable 高等学校等就学支援金_最小 高等学校等就学支援金_最大)
  - 単位制か否かをフロントエンドで入力してもらうことも可能だが、すでに2つフォームがありこれ以上増やすとユーザーの負担が増えてしまう(「全日制、定時制、...」と「公立、私立、...」
- 専攻科は高等学校等就学支援金の対象外のため、別issueで類似制度 `高等学校等の専攻科の生徒への支援` を実装
  - https://www.mext.go.jp/a_menu/shotou/mushouka/1344146.htm

**Comment by SnoozingJellyfish** [comment]
#163 で実装・テスト完了のためクローズします。
特別支援学校等の場合については、フォームの入力項目が増え煩雑になるため一旦非対応としました。
