### ISSUE TITLE
受験生チャレンジ支援貸付事業のバックエンド実装

### ISSUE THREAD

**Issue by Syuparn** [project-inclusive/OpenFisca-Japan#140]
受験生チャレンジ支援貸付事業の算出ロジックを、バックエンドのOpenFisca Python APIで実装・テストします。
単体テストのパターン網羅は別のissueで対応するため、このissueでは最小限のテストで構いません。

https://www.fukushi.metro.tokyo.lg.jp/seikatsu/teisyotokusyataisaku/jukenseichallenge.html

実装方法

- Variable 受験生チャレンジ支援貸付を作成
- 上記を計算するためのVariableを作成
　- 預貯金
　- 塾に通っている

- Variableの作成方法は openfisca_japan/variables/福祉/生活保護.py が参考になりそう
- openfisca_japan/variables/東京都 フォルダにまとめる
- 居住都道府県 が東京都以外の場合は0円とする
- ~~表に書かれているの所得は **年額** のため、OpenFiscaの戻り値である月額に換算して計算する必要あり~~
  - 訂正: `借りられる可能性のあるお金` は月額換算浮揚のためそのまま出力する

**Comment by he23inw3** [comment]
こちら着手します。

**Comment by SnoozingJellyfish** [comment]
PR #151  で完了のためクローズ
