### ISSUE TITLE
受験生チャレンジ支援貸付事業の単体テスト追加

### ISSUE THREAD

**Issue by Syuparn** [project-inclusive/OpenFisca-Japan#141]
受験生チャレンジ支援貸付の額の単体テストファイルを作成します。
openfisca_japan/tests/東京都/福祉 フォルダの定義ファイルを参考に、同フォルダにyamlテストファイルを追加してください。

- https://www.fukushi.metro.tokyo.lg.jp/seikatsu/teisyotokusyataisaku/jukenseichallenge.html

テストケース

- [ ] 子どもの年齢ごとの貸付額
- [ ] 世帯人数ごとの所得上限の境界値テスト(子どもの年齢は固定)
- [ ] 預貯金の境界値テスト
- [ ] 塾に通っている場合

その他必要なものがあれば

**Comment by SnoozingJellyfish** [comment]
PR #151 で完了のためクローズ
