### ISSUE TITLE
GA IDの環境変数化

### ISSUE THREAD

**Issue by AZKZ** [project-inclusive/OpenFisca-Japan#169]
下記のPRでGAを導入したが、本番環境だけではなく開発用の環境でも収集対象になってしまっている。
GA IDを環境変数化して、環境ごとに収集を分けられるようにする。

#161

**Comment by AZKZ** [comment]
## 備忘録
これを機にGTM化しようと思ったが、プレビューがうまく動作しなかったので、後回しにする。
![image](https://github.com/project-inclusive/OpenFisca-Japan/assets/48322521/791f29ca-2abb-470c-bd79-c3508396723e)

ひとまず、このissueはGA IDの環境変数化のみを対象とする。

**Comment by SnoozingJellyfish** [comment]
#172 で対応済みのためクローズします。
