### ISSUE TITLE
parameters配下のcsvファイルをassets配下に移動する

### ISSUE THREAD

**Issue by Syuparn** [project-inclusive/OpenFisca-Japan#181]
バックエンドで使われているパラメータ（`openfisca_japan/parameters` 配下）のうちcsvファイルのみ `openfisca_japan/assets` に移動します。

（Parameters(yamlファイルで表現)はOpenFisca上で制度の定数を表わす仕組みだが、csvファイルは単純に定数値を2次元の表形式で記述しているだけなので区別したい）

変更点

- `assets` ディレクトリの作成（ディレクトリ構成は `parameters` と同じにする)
- バックエンドのcsv読み込み実装のパスを修正

**Comment by SnoozingJellyfish** [comment]
#194 で対応済みのためクローズします。
