### ISSUE TITLE
csvファイル読み込みを関数化

### ISSUE THREAD

**Issue by Syuparn** [project-inclusive/OpenFisca-Japan#182]
バックエンドのcsvファイルを読み込む処理を関数内に記述するようにします。現在はトップレベルで直接ファイル読み込み処理を行っています。

現在の実装 https://github.com/project-inclusive/OpenFisca-Japan/blob/main/openfisca_japan/variables/%E6%89%80%E5%BE%97%E7%A8%8E.py#L27

参考: openfisca_franceの実装 https://github.com/openfisca/openfisca-france/blob/c303e7778b17adbb132138beac3a52a09f0fcac0/openfisca_france/model/prelevements_obligatoires/taxe_habitation/taxe_habitation_import_baremes_locaux.py#L13

読み込み処理関数化でローカル変数のスコープを限定することで、想定外の参照、書き換えを防ぐことが期待されます。

※関数呼び出しにした場合計算のたびにファイル読み込みが走りパフォーマンスが落ちてしまうため、キャッシュも併用したほうが良さそうです。

https://docs.python.org/ja/3.10/library/functools.html

**Comment by Syuparn** [comment]
こちら着手したいと思います。

**Comment by SnoozingJellyfish** [comment]
#196 で対応のためクローズします。
