### ISSUE TITLE
被災者生活再建支援制度のバックエンド実装

### ISSUE THREAD

**Issue by Syuparn** [project-inclusive/OpenFisca-Japan#211]
被災者生活再建支援制度の算出ロジックを、バックエンドのOpenFisca Python APIで実装・テストします。
単体テストについてもこのissueで対応します。

## 実装方法

Variable `被災者生活再建支援制度` を作成

上記を計算するためのVariableを作成

- 住宅被害(Enum)
　	- 全壊
　	- 解体
　	- 長期避難
　	- 大規模半壊
　	- 中規模半壊
- 住宅の再建方法(Enum)
　　- 建設・購入
　　- 補修
　　- 賃借
　　- 未定(加算支援金なし ※後で別途申請するパターン)

## 参考リンク

- https://www.bousai.go.jp/taisaku/seikatsusaiken/pdf/140612gaiyou.pdf 
- https://www.bousai.go.jp/kaigirep/kentokai/saikenshien/pdf/kentou5/siryo3_2.pdf
	- (給付金の使途等、令和5年発行の参考リンク3に記載の内容と異なる記載があるため、古い情報かもしれません)
- https://www.bousai.go.jp/taisaku/hisaisyagyousei/pdf/kakusyuseido_tsuujou.pdf

**Comment by SnoozingJellyfish** [comment]
住宅被害のenumと災害援護資金で使う「滅失または流失」は別variableにしますか？
災害援護資金でも「全壊」「半壊」の情報を使うので、「滅失または流失」も住宅被害のenumに入れても良いかもしれません。
被災者生活再建支援制度では「滅失または流失」も「全壊」と同じ扱いのようです。
https://www.shugiin.go.jp/internet/itdb_shitsumon.nsf/html/shitsumon/a180255.htm

**Comment by Syuparn** [comment]
フロントエンドでは住宅被害は1回しか入力しないと思うので、バックエンドでも同じvarlableにまとめてしまって良いと思います。
（どう対処するかは実装順序にもよりますが、 #212 側に `全体の滅失または流出` を追加するというタスクを記載しています）

> 被災者生活再建支援制度では「滅失または流失」も「全壊」と同じ扱いのようです。

情報ありがとうございます！

**Comment by SnoozingJellyfish** [comment]
承知しました！よろしくお願いします
