### ISSUE TITLE
被災者支援制度見積もりをリリース

### ISSUE THREAD

**Issue by Syuparn** [project-inclusive/OpenFisca-Japan#226]
被災者支援制度見積もり関連機能をリリース(develop -> masterへのマージ)します。

### リリース前にやること

- [x] 災害支援ナビゲーターのリンクを本番用へ差し替え https://github.com/project-inclusive/OpenFisca-Japan/pull/225/files#r1460722628
- [x] 利用規約とプライバシーポリシーの追加

**Comment by SnoozingJellyfish** [comment]
追加で以下もリリース時に行います。

- [ ] README.md に追加した見積もり対象制度を記載。（デプロイするURLが変更される場合はそれも修正）
- [ ] docs/change_log.md に前回リリースからの差分を記載。細かい修正は書ききれないので、追加対応した制度や大きな修正を記載しています。

**Comment by Syuparn** [comment]
以下もリリース時に行います。

- [x] setup.py, requirements.pyをリリース予定バージョンに修正  ( #234 )

**Comment by Syuparn** [comment]
1.2.0リリース完了したのでクローズ
