### ISSUE TITLE
Cypressのテストを改修しやすくする (make Cypress test easier to update)

### ISSUE THREAD

**Issue by Syuparn** [project-inclusive/OpenFisca-Japan#237]
### As Is or how to reproduce if it's bug
（今の状態を記載。不具合・バグの場合、可能であれば再現方法も記載してください。）

フロントエンドのボタンを改修しcypressのテストを修正する際、生成後HTMLの該当要素のIDを探して書き換える必要がある

When the buttons in the frontend is updated, you should rewrite Cypress test by changing HTML IDs.

https://github.com/project-inclusive/OpenFisca-Japan/blob/cddc6b18cee50ecb98543dac6b36aac9b6e809ab/dashboard/cypress/e2e/DetailedCalculation.cy.js#L10

### To Be 
（理想の状態を記載。タスク完了の条件にもなる。）

テストが壊れにくくなるよう、要素のIDを指定せずにテストできるようになる

the test does not require HTML IDs to make it less flaky

### Action
（改善のための具体的なアクションを記載）

### Problem
（現状分かっている課題を記載）

### Note 

イシューに着手した方は、他コントリビューターと重複を防ぐために着手したことをコメントに記載お願いします

**Comment by minagishl** [comment]
こちら着手させていただきます

**Comment by SnoozingJellyfish** [comment]
#250 で対応したためクローズします。
