### ISSUE TITLE
年収inputに書きません

### ISSUE THREAD

**Issue by gminova** [project-inclusive/OpenFisca-Japan#239]
Unable to enter numbers in input field for simple calculation page；same issue with detailed calculation
<img width="347" alt="Screenshot 2024-02-06 at 15 23 31" src="https://github.com/project-inclusive/OpenFisca-Japan/assets/42014388/44dfa2e9-8aa2-4d97-8d13-2314c825d007">

**Comment by SnoozingJellyfish** [comment]
Thank you for your report!
Will you tell me the browser, mobile or PC where the problem occured? 
On my chrome of PC and mobile, I can usually input number. (Sometimes I can't input number by normal keypad, but even then I can input number by numeric keypad.)

**Comment by gminova** [comment]
this was on a MacOS laptop

**Comment by SnoozingJellyfish** [comment]
This issue is closed by #275 merged.
