### ISSUE TITLE
制度一覧の文末表記をそろえる

### ISSUE THREAD

**Issue by Syuparn** [project-inclusive/OpenFisca-Japan#248]
### As Is or how to reproduce if it's bug
現状、「見積もり結果」に出てくる制度の説明で「。」で終わるものとそうでないものが混在しています。

![image](https://github.com/project-inclusive/OpenFisca-Japan/assets/36665200/77041177-82c9-426a-b63f-d8eddb7c7cfa)

### To Be 
全制度の説明文の文末を以下のいずれかに統一します。

- 「。」で終わる
- 「。」なしで終わる

### Action
以下の設定の `caption` を修正

https://github.com/project-inclusive/OpenFisca-Japan/blob/cddc6b18cee50ecb98543dac6b36aac9b6e809ab/dashboard/src/config/app_config.json#L120

### Note 

イシューに着手した方は、他コントリビューターと重複を防ぐために着手したことをコメントに記載お願いします

**Comment by SnoozingJellyfish** [comment]
複数の文での説明は「。」が必要になるので、1つの文だけでも「。」をつけるように統一するのが良いかなと思います。
ただ、`"貸付期間:原則3ヶ月（最長12ヶ月）"`のように、「：」が入っている項目は文ではないので「。」は不要に感じます。

**Comment by minagishl** [comment]
こちら着手させていただきます

**Comment by SnoozingJellyfish** [comment]
#249 で対応済みのためクローズします
