### ISSUE TITLE
/result に直接アクセスするとエラー発生

### ISSUE THREAD

**Issue by SnoozingJellyfish** [project-inclusive/OpenFisca-Japan#252]
### As Is or how to reproduce if it's bug

ローカル環境で /result に直接アクセスすると、世帯情報のstateが定義されていないためエラーが発生します。
<img width="1016" alt="スクリーンショット 2024-03-23 18 41 06" src="https://github.com/project-inclusive/OpenFisca-Japan/assets/78285805/8abf52f1-075c-4e72-9b41-326acc93507d">

netlifyのデプロイURLでは、そもそもSPAのルート以外に遷移できない状態になっています。  
こちらはデフォルトでSPAのルート以外に遷移できるcloudflare pagesに移行することで解決予定。

### To Be 
ローカル環境で /result に直接アクセスすると、エラーページに遷移する。

### Action
エラーページの扱いを修正する。

### Problem
エラー対策は以下でしていたつもりだったが効いていない。
https://github.com/project-inclusive/OpenFisca-Japan/blob/cddc6b18cee50ecb98543dac6b36aac9b6e809ab/dashboard/src/App.tsx#L32

### Note 

結果ページのURLを個別生成する #68 完了後に対応します。

イシューに着手した方は、他コントリビューターと重複を防ぐために着手したことをコメントに記載お願いします

**Comment by minagishl** [comment]
こちら着手させていただきます

**Comment by SnoozingJellyfish** [comment]
#261 で対策されたためクローズします
