### ISSUE TITLE
結果ページ共有URLのQRコードを表示

### ISSUE THREAD

**Issue by SnoozingJellyfish** [project-inclusive/OpenFisca-Japan#254]
### As Is or how to reproduce if it's bug
（#68 対応後、）結果ページのURLを発行・共有できる。
それにより、URLをコピーしてLINE等で送って共有することができるが、チャット・SNSを介す必要がある。

### To Be 
チャットやSNSで繋がっていない人（例えば行政窓口担当者など）に共有する際、QRコードを見せてそれを読み取って、結果ページを表示できるようにする。

### Action
結果ページの共有ボタンを表示したときに、生成されるURLをQRコードに変換して画面に表示する。

### Problem
URLをQRコードに変換するためのライブラリが必要？

### Note 

イシューに着手した方は、他コントリビューターと重複を防ぐために着手したことをコメントに記載お願いします

**Comment by minagishl** [comment]
こちら着手させていただきます

**Comment by SnoozingJellyfish** [comment]
#255 で対応済みのためクローズします
