### ISSUE TITLE
生年月日の代わりに年齢、学年を入力するようにする

### ISSUE THREAD

**Issue by Syuparn** [project-inclusive/OpenFisca-Japan#257]
### As Is or how to reproduce if it's bug
（今の状態を記載。不具合・バグの場合、可能であれば再現方法も記載してください。）

- 見積もりのために、世帯員の生年月日を入力する

### To Be 
（理想の状態を記載。タスク完了の条件にもなる。）

- 自分等は年齢、子どもは学年をフォーム入力する
  - こどもは両方無いと難しい？

### Action
（改善のための具体的なアクションを記載）

- 年齢、学年フォームを用意し、そこから生年月日を計算するように変更
  - 内部的には今日が誕生日として計算するのがシンプル？

### Problem
（現状分かっている課題を記載）

### Note 

イシューに着手した方は、他コントリビューターと重複を防ぐために着手したことをコメントに記載お願いします

**Comment by SnoozingJellyfish** [comment]
子供の場合、年齢と学年それぞれが条件になっている制度があるため、両方の情報が必要になります。（例：[児童手当](https://www.cfa.go.jp/policies/kokoseido/jidouteate/annai/)）
そのため、例えば以下のように年齢と学年に不整合が生じないようなGUIが良いかなと思います。
- 年齢と学年のプルダウンリストをそれぞれ用意
- 両方未入力状態で片方を入力すると、他方はそれと矛盾しない結果を表示
- 片方が入力された状態で他方を入力すると、片方がそれと矛盾しない結果に更新される

**Comment by minagishl** [comment]
こちら着手させていただきます

**Comment by SnoozingJellyfish** [comment]
#262, #263 で対応済みのためクローズします。
