### ISSUE TITLE
年収などのインプットに全角でも入力できるようにする

### ISSUE THREAD

**Issue by minagishl** [project-inclusive/OpenFisca-Japan#274]
### As Is or how to reproduce if it's bug
現在、フォームの年齢, 年収などに半角数字しか入力できない

### To Be 
全角数字で入力した際は半角数字に置き換えるようにする

### Action
正規表現などを利用して実装

### Problem
（現状分かっている課題を記載）

### Note 

イシューに着手した方は、他コントリビューターと重複を防ぐために着手したことをコメントに記載お願いします

**Comment by minagishl** [comment]
着手します

**Comment by SnoozingJellyfish** [comment]
#275 で対応したためクローズします
