### ISSUE TITLE
NetlifyのデプロイサイトをCloudflare Pagesのサイトにリダイレクトする

### ISSUE THREAD

**Issue by SnoozingJellyfish** [project-inclusive/OpenFisca-Japan#300]
### As Is or how to reproduce if it's bug
NetlifyとCloudflare Pagesで別々のwebアプリがデプロイされている。

### To Be 
NetlifyのデプロイサイトをCloudflare Pagesのサイト(https://shien-yadokari.proj-inclusive.org )に301リダイレクトする。

### Action
以下サイトなどを参考に、netlifyの設定ファイルをソース上に作成することでリダイレクトする。
https://docs.netlify.com/routing/redirects/redirect-options/

GithubのPRページにNetlifyのデプロイURLが表示されるので、そこからリダイレクトされるか確認できる？

### Problem
（現状分かっている課題を記載）

### Note 

イシューに着手した方は、他コントリビューターと重複を防ぐために着手したことをコメントに記載お願いします

**Comment by minagishl** [comment]
こちら着手させていただきます

**Comment by SnoozingJellyfish** [comment]
#301 で対応済みのためクローズします
