### ISSUE TITLE
ブロック拠点病院の情報をconfigに追加

### ISSUE THREAD

**Issue by Syuparn** [project-inclusive/OpenFisca-Japan#306]
### As Is or how to reproduce if it's bug
ブロック拠点病院、中核拠点病院等の窓口情報の形式が決まっていない

### To Be 
ブロック拠点病院のデータがソースコード上に入っている

### Action
ブロック拠点病院をconfigに追加

### Problem
（現状分かっている課題を記載）

### Note 

イシューに着手した方は、他コントリビューターと重複を防ぐために着手したことをコメントに記載お願いします

**Comment by Syuparn** [comment]
こちら着手します

**Comment by SnoozingJellyfish** [comment]
#307で対応済みのためクローズ
