### ISSUE TITLE
制限事項と利用規約のページ変更

### ISSUE THREAD

**Issue by SnoozingJellyfish** [project-inclusive/OpenFisca-Japan#333]
**【重要】本イシューに着手する場合、「 dev_new_gui」ブランチをプルした上でコードを修正し、「dev_new_gui」にプルリクエストを出してください。「develop」ブランチにはプルリクエストを出さないでください。**

### As Is or how to reproduce if it's bug
制限事項がトップページに表示されているため初見の情報量が多い。

### To Be 
[figma](https://www.figma.com/design/zZOYORHkS8OZHLZPkf3URG/%E7%84%A1%E9%A1%8C?node-id=707-544&m=dev)の制限事項と利用規約のページのデザインを実装します。
トップページから入力フォームページに遷移するときに、制限事項と利用規約のページを表示して、両方の確認チェックが入ると次に進めるようにします。
制限事項は内部スクロールなし、
利用規約は内部スクロールありにします。
見積もり対象制度一覧は従来のGUIと同じく、アコーディオンで表示します。

**本イシューでは、ヘッダーと下部の「戻る」「次へ」ボタンは実装しません。関連するページが実装されてから、それらも実装します。**

![Screenshot_20240920-123137](https://github.com/user-attachments/assets/dd73c2f7-f209-4640-9d29-46cc7f1903e2)

### Action
`dashboard/src/components/TermsModal.tsx`を修正します。
本イシューではモーダルのままで問題ありません。

### Problem
特になし。

### Note 

イシューに着手した方は、他コントリビューターと重複を防ぐために着手したことをコメントに記載お願いします

**Comment by minagishl** [comment]
着手します

**Comment by SnoozingJellyfish** [comment]
#338 で対応したためクローズします。
以下は今後必要に応じて別イシューを立てて検討します。
- ヘッダーと下部の「戻る」「次へ」ボタン（関連するページが実装されてから）
- 「確認しました」のチェック欄背景を見やすくする方法
