### ISSUE TITLE
見積もり結果を画像に保存する際のファイル名を修正

### ISSUE THREAD

**Issue by Syuparn** [project-inclusive/OpenFisca-Japan#335]
### As Is or how to reproduce if it's bug

- 見積もり結果 `このページを画像で保存` で保存されるファイル名が `お金サポート_結果.png`  (ヤドカリくんの旧名称)になっている

### To Be 

- 保存ファイル名を `見積もり結果.png` にする

### Action
- 以下で定義されたファイル名を修正

https://github.com/project-inclusive/OpenFisca-Japan/blob/1f33933457b9e653a2cedec1b1c774bd94a0b62b/dashboard/src/components/result/result.tsx#L106

- ファイル名定義をconfigへ移動
  - https://github.com/project-inclusive/OpenFisca-Japan/blob/main/dashboard/src/config/app_config.json に定義する

### Note 

イシューに着手した方は、他コントリビューターと重複を防ぐために着手したことをコメントに記載お願いします

**Comment by minagishl** [comment]
こちら着手します

**Comment by minagishl** [comment]
#349 で対応したためクローズします
