### ISSUE TITLE
LINE Botのリンクをドキュメントに追加

### ISSUE THREAD

**Issue by Syuparn** [project-inclusive/OpenFisca-Japan#340]
### As Is or how to reproduce if it's bug
開発者向けドキュメントからLINE Botへアクセスしづらい

### To Be 
ドキュメントから直接LINE Botへアクセスできる

### Action
友達登録のリンクを https://github.com/project-inclusive/OpenFisca-Japan/blob/1f33933457b9e653a2cedec1b1c774bd94a0b62b/docs/chat_bot.md のページに追加

- リンク
  - https://www.proj-inclusive.org/#h.yp586wvuwsln の LINE Botのリンクと同じもの

### Problem
（現状分かっている課題を記載）

### Note 

イシューに着手した方は、他コントリビューターと重複を防ぐために着手したことをコメントに記載お願いします

**Comment by kanta10250** [comment]
着手します。

**Comment by Syuparn** [comment]
追記いただいたのでクローズします
