### ISSUE TITLE
市区町村級地区分の設定ファイルの作成

### ISSUE THREAD

**Issue by SnoozingJellyfish** [project-inclusive/OpenFisca-Japan#36]
生活保護や生活福祉資金貸付制度の算出に必要な市区町村級地区分の設定ファイルを作成します。
市区町村は「1級地-1」、「1級地-2」、「2級地-1」、「2級地-2」、「3級地-1」、「3級地-2」の6つに分類されます。
以下のリンクに記載されている「3級地-2」以外の市区町村名をもとに、`openfisca_japan/parameters/市区町村級地区分.json`に記載してください。
https://best-selection.co.jp/media/wp-content/uploads/2021/03/seikatsuhogo-kyuchi2022.pdf
フォーマットは市区町村級地区分.json内の例の通り、m級地-n の場合
{ *都道府県名* : {*市区町村名*: [m, n], ...}, ...}
としてください。
「3級地-2」の市町村はその他の市町村として扱うことができるため、記載不要です。

**Comment by minosys-jp** [comment]
@minosys-jp @SnoozingJellyfish 
着手したいと思います。２〜３日でできそうな予感。
