### ISSUE TITLE
生活保護のバックエンド実装・テスト

### ISSUE THREAD

**Issue by SnoozingJellyfish** [project-inclusive/OpenFisca-Japan#39]
生活保護支給額の算出ロジックを、バックエンドのOpenFisca Python APIで実装・テストします。
実装の流れは `openfisca_japan/variables/福祉/生活保護.py` を参照してください。
各種設定ファイルは `openfisca_japan/parameters/福祉/生活保護` フォルダ以下にcsv, yamlファイル等で作成します。
生活保護の算出はステップ数が多いため、世帯情報をインプット、支給額をアウトプットにしたテストではなく、
各ステップごとの単体テストを行います。インプットは本来何かのアウトプットとなる情報でもテストファイルに定義可能です。（所得等）　テスト方法は基本は境界値テストですが、各種設定ファイルの表項目は数が多いので代表的なパターンのテストで構いません。
単体テストファイルは `openfisca_japan/tests/福祉/生活保護` フォルダ以下に作成してください。

**Comment by Syuparn** [comment]
こちら実装進めていきたいと思います。

**Comment by Syuparn** [comment]
@SnoozingJellyfish 
1PRにまとめると差分が大きくなりそうだったので、まず全体的な計算式の部分の実装まででPR作成しました（各ステップのVariableはダミー値）。

https://github.com/project-inclusive/OpenFisca-Japan/pull/60

各ステップのVariable（csv読み込み）は追って実装します。

**Comment by SnoozingJellyfish** [comment]
@Syuparn 
PRありがとうございます！　実装方針良い感じだと思います。
項目が多いテストファイルを作る別issue  #61 を作成したので、syupernさんの方ではひとまず内部ロジックの実装からやっていただければと思います。 （項目が少ないテストファイルはロジック実装しながら作った方がデバッグしやすいと思うので、issueでは取り上げていません）
variableの粒度はテストしやすいようできるだけ小さくしているので、最新developの `openfisca_japan/tests/福祉/生活保護` フォルダ以下のテストファイルのvariable例を参考に実装いただけると助かります。

**Comment by Syuparn** [comment]
@SnoozingJellyfish
承知しました。それでは内部ロジックのvariable実装進めていきたいと思います。
(PRのコメントいただいた文言の部分も修正しました）

**Comment by Syuparn** [comment]
@SnoozingJellyfish 
csvを使用したvariableロジック実装のPR作成しました。`openfisca_japan openfisca_japan/tests/福祉/生活保護/` 配下の全テスト成功を確認済みです。

#66

**Comment by Syuparn** [comment]
@SnoozingJellyfish 

TODOにしていた加算の部分も実装しました。このissueではおそらく最後のPRになると思います。
#67

**Comment by SnoozingJellyfish** [comment]
@Syuparn 
`openfisca_japan/variables/福祉/生活保護.py`の1004行目でTODOとなっている「10人以降の場合の1人当たり加算額を追加」について、対応いただくことは可能でしょうか？
現時点では世帯人数が10人以上の場合に一律で1000円程度の加算額のみ支給する実装になっていますが、正しくは9人の場合の加算額にその額を加える実装になるかと思います。

**Comment by Syuparn** [comment]
@SnoozingJellyfish 

TODO対応漏れていました。こちらで修正しましたのでご確認お願いします。

https://github.com/project-inclusive/OpenFisca-Japan/pull/83

**Comment by SnoozingJellyfish** [comment]
バックエンド実装完了しテスト合格したためクローズします。
