### ISSUE TITLE
生活保護の設定ファイルを作成

### ISSUE THREAD

**Issue by SnoozingJellyfish** [project-inclusive/OpenFisca-Japan#45]
`openfisca_japan/parameters/福祉/生活保護`フォルダ以下に作成している、生活保護の算出に必要な各種設定ファイルを完成させます。
それぞれ以下のリンクを参照して、空白欄を埋めてください。

- [x] [住宅扶助基準額](http://kobekoubora.life.coocan.jp/2021juutakufujo.pdf): 都道府県(p.1\~3), 市(p.4\~6)
- [x] [生活扶助基準額](https://www.mhlw.go.jp/content/000776372.pdf): p.1 左
- [x] [生活扶助本体における経過的加算](https://www.mhlw.go.jp/content/000776372.pdf): p.2 左
- [x] [冬季加算](https://www.mhlw.go.jp/file/05-Shingikai-12601000-Seisakutoukatsukan-Sanjikanshitsu_Shakaihoshoutantou/26102103_6.pdf)
- [x] [母子世帯等に係る経過的加算](https://www.mhlw.go.jp/content/000776372.pdf): p.2 右上
- [x] [期末一時扶助](https://seikatsuhogo.biz/blogs/61)

**Comment by minosys-jp** [comment]
生活扶助基準額から進めることにします。

**Comment by he23inw3** [comment]
@SnoozingJellyfish 
[期末一時扶助](https://seikatsuhogo.biz/blogs/61)を着手いたしました。
この後PRを出すようにいたします。

**Comment by he23inw3** [comment]
@SnoozingJellyfish 
[期末一時扶助](https://seikatsuhogo.biz/blogs/61)のCSVを作成しPR作成いたしました。
お手すきの際にRvお願いいたします。
https://github.com/project-inclusive/OpenFisca-Japan/pull/50

**Comment by minosys-jp** [comment]
生活扶助基準額の PR を作成しました。

**Comment by minosys-jp** [comment]
次は生活扶助本体における経過的加算に着手したいと思います。

@he23inw3 
分担どうしましよう？

**Comment by SnoozingJellyfish** [comment]
@minosys-jp , @he23inw3 
進捗ありがとうございます！　PRマージしました。
ちなみに効率的にファイルを作成するやり方があれば、教えていただけるとありがたいです。
（PDFは目視で写すか１個ずつコピペするしかないですかね…？）

**Comment by minosys-jp** [comment]
@SnoozingJellyfish 
自分はテキストファイルにコピペして sed で整形しています。
原始的なやり方ですが、PDF からデータを取得するのがちと面倒だし、機械的な作業なのでまあ良いかと。

**Comment by he23inw3** [comment]
すみません、返信遅れました。

@minosys-jp 
次は [母子世帯等に係る経過的加算](https://www.mhlw.go.jp/content/000776372.pdf): p.2 右上 を着手いたします。
概要に6項目提示いただいていると思うので、下から冬季加算まで順次着手しようと思います。
※念のため開始前にアナウンスして、作業かぶりしないようにする予定です。

@SnoozingJellyfish 
先日実施した[期末一時扶助](https://seikatsuhogo.biz/blogs/61)については、件数が少ないのとWebページでしたので、各値をコピペで対応しています。

**Comment by minosys-jp** [comment]
@SnoozingJellyfish 
生活扶助本体における経過的加算 PR 作成しました。

@he23inw3 
次は住宅扶助基準額に着手します。

**Comment by SnoozingJellyfish** [comment]
@minosys-jp @he23inw3 
なるほど、スクショを取ってOCRできるかも？など思ったのですが、やはりコピペの方が早そうですね！
引き続きよろしくお願いします。

**Comment by he23inw3** [comment]
@SnoozingJellyfish 
[母子世帯等に係る経過的加算](https://www.mhlw.go.jp/content/000776372.pdf): p.2 右上のPRを作成しました。
Rvを宜しくお願い致します。

**Comment by he23inw3** [comment]
@minosys-jp 
次は[冬季加算](https://www.mhlw.go.jp/file/05-Shingikai-12601000-Seisakutoukatsukan-Sanjikanshitsu_Shakaihoshoutantou/26102103_6.pdf)に着手します。

**Comment by he23inw3** [comment]
@SnoozingJellyfish
[冬季加算](https://www.mhlw.go.jp/file/05-Shingikai-12601000-Seisakutoukatsukan-Sanjikanshitsu_Shakaihoshoutantou/26102103_6.pdf)の[PR](https://github.com/project-inclusive/OpenFisca-Japan/pull/65)を作成しました。
Rvを宜しくお願い致します。

**Comment by SnoozingJellyfish** [comment]
@minosys-jp , @he23inw3 
お二人ともありがとうございました！全ファイルできたのでクローズします。
