### ISSUE TITLE
OpenFisca開発に関するオンボーディングドキュメント作成する

### ISSUE THREAD

**Issue by AZKZ** [project-inclusive/OpenFisca-Japan#48]
# 概要

- 新たなメンバーがOpenFiscaの開発タスクに着手する際のハードルを下げられるようなドキュメントを作成する

# 目的

- OpenFiscaの開発タスクに着手する際のハードルを下げて、開発に参加してもらいやすくするため

# 対応内容

- WikiやREADMEに既に記載されている情報の整理
- OpenFiscaの簡単なチュートリアルの作成

**Comment by AZKZ** [comment]
@SnoozingJellyfish 

> WikiやREADMEに既に記載されている情報の整理

情報整理の方針については下記のように考えてます。
何かご意見があればお願いします。

- README → まず最初に知ってほしい情報
  - マイ制度シミュレーターの説明
  - ローカル環境構築方法
- Wiki → 細かく説明したい情報
  - OpenFiscaとは
  - 開発の参加方法
  - OpenFiscaのチュートリアル
  - など

**Comment by SnoozingJellyfish** [comment]
@AZKZ 
整理ありがとうございます！  
わかりやすいと思います。  
issueによってはdockerの環境構築が不要なものもあるので、READMEに「開発の参加方法」を記載し、wikiに「ローカル環境構築方法」を記載するのはいかがでしょうか？

**Comment by AZKZ** [comment]
@SnoozingJellyfish 

確認ありがとうございます！

色々確認したところWikiだとプルリクエストが作成できず、運用が面倒になりそうです。（コミッターのハードルも上がりそう）
なので、既存のDocフォルダにまとめたいなと思います。

マイ制度シミュレーターでGithub Pagesを使わなくなるようでしたら、今後Docフォルダをホストするのもありかなと思いますがいかがでしょうか？

--- 

> issueによってはdockerの環境構築が不要なものもあるので、READMEに「開発の参加方法」を記載し、wikiに「ローカル環境構築方法」を記載するのはいかがでしょうか？

確かにdockerの環境構築はMustではないのでREADMEに「開発の参加方法」を記載し、「ローカル環境構築方法」はDocフォルダ内にまとめようと思います！

**Comment by SnoozingJellyfish** [comment]
@AZKZ 
Docフォルダにまとめる旨、承知しました！

Github pagesはもう使わないので、ドキュメント閲覧用にホストしていただいて大丈夫です。
github pagesでmarkdownをホストできるんですね！
更新頻度が高いdevelopブランチプッシュ時にホストされるのが良いかなと思います。
権限が必要でしたら付与します。
