### ISSUE TITLE
生活保護のフロントエンド実装

### ISSUE THREAD

**Issue by SnoozingJellyfish** [project-inclusive/OpenFisca-Japan#49]
[Figma](https://www.figma.com/file/izSZUKF9r19BwkEnUZhHrM/%E3%83%9E%E3%82%A4%E5%88%B6%E5%BA%A6%E3%82%B7%E3%83%9F%E3%83%A5%E3%83%AC%E3%83%BC%E3%82%BF%E3%83%BC?type=design&node-id=0%3A1&mode=design&t=ArZGglM6HWTQMfIt-1)のフォーム画面・結果画面のGUIをもとに、生活保護制度のフロントエンドを作ります。  
- [issue#39](https://github.com/project-inclusive/OpenFisca-Japan/issues/39) のバックエンド実装で新たに必要になった情報をフォームに追加します。
- 「給付されるお金」に「児童手当」と同様に「生活保護」のプルダウンを作成します。  
結果画面の説明に以下の文言を記載します。  
「家賃や水光熱費、食費、医療費、教育費などのふつうに暮らすために必要なお金の給付。 働いて収入がある場合も、働いていない場合も対象になります。算出された額に加え、医療費・介護費等が実費で給付されます。」. 
「詳細リンク」のリンク先はhttps://www.mhlw.go.jp/stf/seisakunitsuite/bunya/hukushi_kaigo/seikatsuhogo/seikatsuhogopage.html としてください。
- 「給付されるお金」欄の各手当を、金額の小さい順に並び替えて表示します。

**Comment by Syuparn** [comment]
フロントエンド実装しましたので、お手すきの際にご確認お願いします。

https://github.com/project-inclusive/OpenFisca-Japan/pull/84

**Comment by SnoozingJellyfish** [comment]
@Syuparn 
かなりのボリューム実装いただきありがとうございました！　動作確認できたので本issueをクローズします。
