### ISSUE TITLE
東京都の制度調査

### ISSUE THREAD

**Issue by SnoozingJellyfish** [project-inclusive/OpenFisca-Japan#53]
都知事杯に向けて東京都独自の制度を調査します。
Code for Japan Slackのproj-inclusiveチャネルのピン留めアイテム「What's going on in proj-inclusive」の scrapboxにリンクを貼っている「生活困窮者支援制度リスト」スプレッドシートの「東京都制度」に追記ください。
各制度につき、重要度や実装難易度、適用条件等を主観で良いので記入ください。
その調査結果をもとに、メンバーで議論の上、実装する制度を3~5個程度に絞り込み、優先順位をつけたいと思います。

以下のサイト等に情報がありそうです。他のサイトを調査していただいても構いません。
- [東京都福祉局](https://www.fukushi.metro.tokyo.lg.jp/)
- [東京都オープンデータカタログサイト](https://portal.data.metro.tokyo.lg.jp/)：制度自体の情報はあまりないかもしれませんが、問い合わせ窓口は記載されており、そのリンクをアプリに載せられそうです。

**Comment by Syuparn** [comment]
都知事杯対応分としては実装完了しているのでクローズ。別制度を追加する場合は改めてマイルストーンを作成する。
