### ISSUE TITLE
数値のinputでバックエンド過負荷が発生しないようにする

### ISSUE THREAD

**Issue by SnoozingJellyfish** [project-inclusive/OpenFisca-Japan#6]
現在、フロントエンドではフォームの入力情報が1つでも変更されると検索結果が更新されます。そのため、数値フォームのspinner(矢印ボタン)で値を増減させると、変化させた分だけの回数バックエンドへリクエストが飛んでしまいます。

例：年収フォームを矢印で100万から200万に増加させると、100回リクエストが発生（ローカルで検証）

![image](https://user-images.githubusercontent.com/36665200/232930725-303f3e09-9ec0-40cc-90df-efee421daf1a.png)

数秒の間に数百のリクエストが発生しバックエンドに負荷がかかるため、

1. 数値を確定してからリクエストするようにする
2. フォームの矢印を消し、手入力しかできないようにする

のような対応が必要と考えています。

**Comment by SnoozingJellyfish** [comment]
報告ありがとうございます。  
年収フォームの修正だけでなく、全体のPOSTタイミングも見直してもいいかもしれません。  
ユーザーが実際に使用する際は、入力条件をあれこれ変えてみたりせず、自分の世帯情報をわかる範囲で入力しきってから結果が出る、というのでも問題ないように感じます。  
そのため、入力フォームの下に確定ボタンを設け、それが押されたタイミングでOpenFisca APIにPOSTされるというのでも良いかもしれません。それによって、ページが変わるか結果欄に自動スクロールされれば、結果がいつ更新されたか分かるようにもなります。

**Comment by Syuparn** [comment]
コメントありがとうございます。確かに数値以外のリクエストも必要数に絞っておいた方が後々良さそうですね。
こちら他に誰か着手中でなければ、確定ボタンの実装を進めたいと思います。
