### ISSUE TITLE
生活保護の単体テストファイル作成

### ISSUE THREAD

**Issue by SnoozingJellyfish** [project-inclusive/OpenFisca-Japan#61]
生活保護の単体テストファイルを作成します。
`openfisca_japan/parameters/福祉/生活保護`フォルダの定義ファイルを参考に`openfisca_japan/tests/福祉/生活保護` 以下のyamlテストファイルに追記してください。
基本的に以下のポリシーで単体テストを行います。

- できるだけ細かい粒度でテストする（条件の組み合わせを減らすため）
- 境界値テスト
- m行n列の表項目は、m行1列, 1行n列の m + n の組み合わせをテストする。（住宅扶助基準を除く）

- [x] 住宅扶助基準額
- [x] 生活扶助基準額
- [x] 生活扶助本体における経過的加算
- [x] 冬季加算
- [x] 母子世帯等に係る経過的加算
- [x] 期末一時扶助

すでに記載している例が間違っているかもしれないので、その場合は修正いただけると助かります。

**Comment by he23inw3** [comment]
住宅扶助基準額を着手します。

**Comment by SnoozingJellyfish** [comment]
着手ありがとうございます！
m×1 + 1×n の m + n パターンのテストを作成していただきたいです。
内部でcsvを2次元配列として読み込んでいるので、縦・横1行ずつ確認したいという意図です。

**Comment by he23inw3** [comment]
@SnoozingJellyfish 
[PR](https://github.com/project-inclusive/OpenFisca-Japan/pull/76)のご確認及びmergeありがとうございます。
生活扶助基準額に着手します。

**Comment by he23inw3** [comment]
@SnoozingJellyfish 
生活扶助基準額の単体テストについて、[PR](https://github.com/project-inclusive/OpenFisca-Japan/pull/78)を作成しました。
お手すきでご確認お願いいたします。

生活扶助本体における経過的加算に着手します。

**Comment by he23inw3** [comment]
@SnoozingJellyfish 
生活扶助本体における経過的加算の単体テストについて、[PR](https://github.com/project-inclusive/OpenFisca-Japan/pull/80)を作成しました。
お手すきでご確認お願いいたします。

冬季加算に着手します。

**Comment by he23inw3** [comment]
@SnoozingJellyfish
冬季加算の単体テストについて、[PR](https://github.com/project-inclusive/OpenFisca-Japan/pull/81)を作成しました。
お手すきでご確認お願いいたします。

母子世帯等に係る経過的加算に着手します。

**Comment by he23inw3** [comment]
@SnoozingJellyfish 
母子世帯等に係る経過的加算について、生活保護.pyの修正対応とhttps://github.com/project-inclusive/OpenFisca-Japan/issues/39#issuecomment-1678565170 の対応でコンフリクトが発生しそうでしたので、
先に期末一時扶助の単体テストファイルを作成いたしました。
お手すきの際に[PR](https://github.com/project-inclusive/OpenFisca-Japan/pull/85)の確認を宜しくお願いいたします。

**Comment by he23inw3** [comment]
@SnoozingJellyfish 
母子世帯等に係る経過的加算について、生活保護.pyの各種修正と単体テストファイルの作成が完了しました。
お手すきの際に、[PR](https://github.com/project-inclusive/OpenFisca-Japan/pull/86)の確認を宜しくお願いいたします。

**Comment by SnoozingJellyfish** [comment]
@he23inw3 
かなりの量のテストを作成いただきありがとうございました！
全テスト合格し生活保護の実装が完了したため本issueをクローズします。
