### ISSUE TITLE
入力条件ごとに結果の個別URLを作成する (Create a separate URL for results by each input information)

### ISSUE THREAD

**Issue by SnoozingJellyfish** [project-inclusive/OpenFisca-Japan#68]
入力条件ごとに結果画面の個別URLを作成します。これにより、結果画面のURLを保存しておけば、後から再度世帯情報を入力することなく、いきなり結果画面を表示することが可能になります。

1. `dashboard/src/App.tsx`で `/result`にchildrenを設定し、dynamic routingさせるようにする。
1. `dashboard/src/components/forms/formContent.tsx`で「計算する」ボタンが押された時、householdを圧縮・エンコードして個別URLを生成し、そこに遷移する。
圧縮・エンコードは、例えば[zlib.js](https://github.com/imaya/zlib.js/)等のライブラリを用いて可逆圧縮し、base64で文字列にすることができそう。
「かんたん計算」モードと「くわしく計算」モードの区別を示す`isSimpleCalculation`もURLで表現する必要があります。
1. `dashboard/src/components/result/result.tsx` でURLをデコードしてhouseholdを復元する。
1. 結果画面に「URLをコピー」ボタンを置き、押された場合はURLをクリップボードにコピーする。
<img width="385" alt="URLコピーボタン" src="https://github.com/project-inclusive/OpenFisca-Japan/assets/78285805/aae5371c-5960-4cb0-ac42-84421b955c23">

***

(In English)
Create a separate URL for the result page for each input condition. As a result, if users save the URL of the result page, they can immediately display the result page without having to enter the household information again later.

1. Set children to `/result` in `dashboard/src/App.tsx` to enable dynamic routing.
1. When the "Calculate" button is pressed in `dashboard/src/components/forms/formContent.tsx`, compress and encode household to generate an separate URL and transition there.
For compression and encoding, it seems possible to use a library such as [zlib.js](https://github.com/imaya/zlib.js/) for lossless compression and convert it to a string with base64.
`isSimpleCalculation`, which indicates the difference between "simple calculation" mode and "detailed calculation" mode, must also be expressed in the URL.
1. Restore the household by decoding the URL in `dashboard/src/components/result/result.tsx`.
1. Place a "Copy URL" button on the result page, and copy the URL to the clipboard when pressed.

**Comment by SnoozingJellyfish** [comment]
@Syuparn 
情報ありがとうございます！　確かにhouseholdを丸ごとエンコード・デコードする方が簡単で分かりやすいですね。
挙げていただいたリンク先ではZIP圧縮に用いられるdeflateアルゴリズムを使って圧縮しているようなので、同じように圧縮するライブラリ等使えば実現できそうです。
ちなみに手元でhouseholdのサンプルjsonを圧縮→base64で文字列化すると500〜1000文字くらいで、LINE上で1~2スクロールくらいでした。少し長いですが、[お悩みハンドブックの詳細結果画面](https://compass.graffer.jp/handbook/solutions/10003?100=0&101=0&102=1&103=0&104=0&105=0&106=0&107=0&10025=1&10026=0&10027=1&10028=0&10029=1&10030=1&20001=1&20002=1&20003=1&20004=1&20005=0&20006=0&20007=0&20008=1&20009=1&20010=1&20011=1&20012=1&20013=1&20014=1&20015=1&20016=0&20017=1&20018=0&20019=1&20020=1&20021=0&20022=0&20023=0&20024=0&20025=1&20026=1&20027=0&20028=1&20029=1&20030=1&20031=1&20032=1&20033=0&20034=1&30001=0&30002=0&30003=1&30004=1&30005=1&30006=1&30007=1&30008=1&30009=1&30010=1&30011=0&30012=0&30013=0&30014=0&30015=0&60001=0&60002=0&60003=1&60004=1&60005=1&60006=1&60007=0&70001=0&70002=1&70003=1&70004=0&70005=0&80001=1&80002=1&80003=1&80004=1&80005=1&80006=0&90001=1&90002=1&90003=1&90004=1&90005=1&90006=1&90007=0)のURLも700字くらいで、コピペするのであれば問題ない気がします。

**Comment by SnoozingJellyfish** [comment]
ユーザーごとのデータベースを持つ方がシンプルな設計になるが、セキュリティやプライバシーの考慮が必要なため検討継続。

Having a database for each user would be a simpler design, but security and privacy considerations need to be considered, so we are continuing to consider this.

**Comment by minagishl** [comment]
こちら着手させていただきます

**Comment by SnoozingJellyfish** [comment]
#253 で対応済みのためクローズします
