### ISSUE TITLE
生活福祉資金貸付制度の実装

### ISSUE THREAD

**Issue by SnoozingJellyfish** [project-inclusive/OpenFisca-Japan#7]
生活福祉資金貸付制度は、生活や就業、学業などに必要なお金を無利子や低い利息で借りられる公的な貸付制度です。  
以下の実装を行います。

### 実装例
`openfisca_japan/variables/福祉/生活福祉資金貸付制度.py`に生活支援費のvariableを実装したので、他の種類の費用の実装はそれを参考にしてください。  

### 算出ロジック
生活福祉資金貸付制度の計算に用いる条件は以下3つ
  - ①低所得者世帯：必要な資金を他から借り受けることが困難な世帯（市町村民税非課税程度）
    - 市町村民税非課税基準は[リンク](https://financial-field.com/tax/entry-173575)の＜所得割と均等割両方が非課税になる世帯＞を参照。
    - 基準は厳密には市町村ごとに異なるが、東京23区の基準を採用する。
    - 判定に用いる総所得金額は、「年収 - 給与所得控除」の額とする。（全種類の所得や控除を元に厳密に算出するのは難しいため）
  - ②障害者世帯：身体障害者手帳、療育手帳（愛の手帳）、精神障害者保健福祉手帳の交付を受けた者等の属する世帯
    - 手帳の等級は問われないはず
  - ③高齢者世帯：65歳以上の高齢者の属する世帯
    - 世帯員が1人でも65歳以上の場合
    - entityに祖父母を追加する必要がある

上記の条件を用いて以下のロジックで、適用される費用のvariableは上限金額を返し、適用されない費用のvariableは0を返す。

1. ①市町村民税非課税程度の所得以下、②障害者手帳を持つ、③65歳以上と同世帯、のいずれかを満たす場合
    - 生活支援費（生活再建までの間に必要な生活費用）：月 〜20万円
    - 一時生活再建費（生活再建までの間に一時的に必要な生活費用）：〜60万円
    - 福祉費（様々な用途で必要なお金）：〜580万円
    - 緊急小口資金（緊急かつ一時的に生計の維持が困難となった場合に借りられる資金）：〜10万円
    - 住宅入居費（家の賃貸契約を結ぶために必要な費用）：〜40万円
1. 条件1の①低所得世帯を満たした条件で、子供がいる場合は以下を追加
    - 教育支援費（高校、大学等で学ぶために必要な費用）：月 〜10万円. 
    **（子供が高校1年生以上であることが条件）**
    - 就学支度費（高校、大学等の入学に必要な費用）：〜50万円. 
    **（子供が中学3年生以上であることが条件）**
1. 条件1の①低所得世帯かつ②高齢者世帯を満たした条件で、65歳以上の高齢者がいる場合は以下を追加
    - 不動産担保型生活資金（不動産を担保として借りられる生活資金）：月〜30万円

※要保護世帯向け不動産担保型生活資金は貸付限度額が固定額でないため省略

- テストも行う。

## フロントエンド（React）
- 入力項目の追加
  - 「親あるいは祖父母と同居している」というチェックボックスを設け、そのチェックが入った場合に親あるいは祖父母の生年月日・収入・障害のフォームを表示する. 
  新たな世帯員フォームの追加は`dashboard/src/components/forms/attributes/ChildrenNum.tsx`を参考にしてください。
  - 「あなた」のコンポーネントに「家を借りたい」のチェックボックスを追加

- 生活福祉資金貸付制度のいずれかの種類の費用がバックエンドAPIにより適用される場合、以下を表示する
  - 「生活福祉資金貸付制度」自体の表記と簡単な説明（「原則無利子・無担保でお金を借りられ、サポーターの支援も受けられる制度」等）
  - 生活福祉資金貸付制度の詳細説明のリンク
  - 適用される費用の表示
    - 「家を借りたい」のチェックボックスにチェックが入る→住宅入居費が適用される場合は表示
    -  0円が返ってきた費用は表示しない。
- 「生活福祉資金貸付制度の詳細は市町村社会福祉協議会または都道府県社会福祉協議会にお問い合わせください。」の文言

**Comment by SnoozingJellyfish** [comment]
## 制度算出ロジックの修正
- 「教育支援費」は高校生以上が対象となるので、貸付条件に「学年が高校1年生以上の世帯員がいる」を付け加えたいと思います。世帯員の学年の呼び出し方法は`openfisca_japan/variables/福祉/育児/児童手当.py`を参考にしてください。
- 「就学支度費」は高校以上に入学する場合に対象となるので、貸付条件に「学年が中学3年生以上の世帯員がいる」を付け加えたいと思います。

## バックエンドのテスト方法

6/18 17:00以降のmainブランチをプルした上でテストを実行してください。

`make_tests/テストパターン/生活福祉資金貸付制度.csv`に記載したテストパターンを元に、テストのyamlファイルを自動作成し、テストを実施する流れを以下に記載します。

1. `make_tests/mylib/mymodule/kosodate_teate.py`を参考に、生活福祉資金貸付制度用のテスト自動生成スクリプトを作成します。基本的には`kosodate_teate.py`をそのままコピーした内容で問題ないですが、子育て支援制度専用の項目を削除し、生活福祉資金貸付制度専用の項目（住民税非課税世帯等）を追加する必要があります。
1. `make_tests/generate.sh`で作成した生活福祉資金貸付制度テスト自動生成スクリプトを実行します。  
`openfisca_japan/tests/generated`フォルダにテストのyamlファイルが自動生成されます。
1. READMEの「開発方法 - バックエンド」に記載の方法で、生成したテストファイルを元にテストを行なってください。




### 備考
- 「生活福祉資金貸付制度.csv」は[厚労省のHP](https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/hukushi_kaigo/seikatsuhogo/seikatsu-fukushi-shikin1/kashitsukejoken.html)を参照して境界値法で作成しています。  
ただし、そもそもの制度が複雑かつ曖昧な部分があるため、ある種アドホック的にパターンを作成しています。  
テスト結果自体が間違っていたり、追加のパターンが必要な可能性もあるので、その場合は適宜修正・追加していただけると助かります。
- テスト方法で詰まるところなどあれば、本リポジトリwikiの「OpenFiscaのTips」を参照してください。  
variableのpythonファイル内で意図的に文法エラーを発生させると、標準出力が表示されるため、printデバッグが可能になります。  
その他、気づいた点やドキュメントに残しておいた方が良いことがあれば、`Doc/dev_note.md`に追記していただけるとありがたいです。

**Comment by AZKZ** [comment]
@SnoozingJellyfish 
こちら対応が遅くなりすみません🙇🏻‍♂️
バックエンドの実装に着手し始めたところです。
「福祉費」について相談させてください。

--- 

「福祉費」は用途によって上限額が変わるようです。
https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/hukushi_kaigo/seikatsuhogo/seikatsu-fukushi-shikin1/kashitsukejoken.html
![image](https://github.com/project-inclusive/OpenFisca-Japan/assets/48322521/0ae56ae6-806e-4882-86e3-b6fb6322179a)

https://www.mhlw.go.jp/bunya/seikatsuhogo/fukushihi.html
<img width="1395" alt="image" src="https://github.com/project-inclusive/OpenFisca-Japan/assets/48322521/848d00c2-5494-431b-9c79-30cecc6ef1a8">

バックエンドでどこまで対応するかについて相談したいです。
下記のどちらかだと思いますが、いかがでしょうか？
- 全ての用途について、バックエンド側で実装する
  - ※この場合、参考になるような実装をしている部分があれば教えていただきたいです
- ひとまず上限額を出して、詳細はリンクから遷移して確認してもらえるようにする
  - リンクは他の資金と同様に[こちら](https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/hukushi_kaigo/seikatsuhogo/seikatsu-fukushi-shikin1/kashitsukejoken.html)でいいかなと思っています。そこには用途別金額のページリンクもあるので。

**Comment by SnoozingJellyfish** [comment]
@AZKZ 
着手ありがとうございます！　PRの実装もそのまま進めていただいて良いかと思います。  

福祉費の用途については、後者のご提案の方が良いかなと思います。
> ひとまず上限額を出して、詳細はリンクから遷移して確認してもらえるようにする
> リンクは他の資金と同様に[こちら](https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/hukushi_kaigo/seikatsuhogo/seikatsu-fukushi-shikin1/kashitsukejoken.html)でいいかなと思っています。そこには用途別金額のページリンクもあるので。

ユーザーに各用途についてチェックしてもらうのはかなり煩雑だと思うので…。

**Comment by AZKZ** [comment]
@SnoozingJellyfish 
ご確認ありがとうございます！

> ひとまず上限額を出して、詳細はリンクから遷移して確認してもらえるようにする
上記で進めさせていただきます！

**Comment by AZKZ** [comment]
@SnoozingJellyfish 

https://github.com/project-inclusive/OpenFisca-Japan/pull/25
バックエンドの実装について、上記でPRを作成しました。
ご確認のほどよろしくお願いいたします🙇🏻

**Comment by SnoozingJellyfish** [comment]
@AZKZ さんのPRをマージしました。ありがとうございます。
私の方でentityを整備するので、フロントエンド実装はしばしお待ちください。

**Comment by SnoozingJellyfish** [comment]
@Syuparn 
祖父母のentityを追加したので、フロントエンド実装ができる状態になりました。
フォームで入力する「同居している親または祖父母」の情報は祖父母のentityに設定してください。

**Comment by SnoozingJellyfish** [comment]
バックエンド・テスト・フロントエンドの実装が完了したためクローズします。
