### ISSUE TITLE
重度心身障害者手当のバックエンド実装

### ISSUE THREAD

**Issue by Syuparn** [project-inclusive/OpenFisca-Japan#88]
重度心身障害者手当の算出ロジックを、バックエンドのOpenFisca Python APIで実装・テストします。
単体テストのパターン網羅は別のissueで対応するため、このissueでは最小限のテストで構いません。

https://www.fukushi.metro.tokyo.lg.jp/shinsho/teate/juudo.html

**Comment by SnoozingJellyfish** [comment]
@Syuparn 
イシュー作成ありがとうございます！
東京都独自の制度は、`variables`フォルダ直下に`東京都`フォルダを作成し、そこにまとめるのが分かりやすいかなと思いました。置き場所は後から自由に変えられるので、今後制度が増えてきたらまた整理可能です。

また、東京都独自の制度は居住都道府県が東京都以外の場合は0円で算出されるのが良さそうです。

**Comment by Syuparn** [comment]
@SnoozingJellyfish 
共有ありがとうございます！高等学校奨学給付金のissueにもこちらの内容記載したいと思います。

**Comment by Syuparn** [comment]
（引き続き、こちら着手したいと思います）

**Comment by SnoozingJellyfish** [comment]
PR #125 でテスト完了のためクローズ
