### ISSUE TITLE
重度心身障害者手当のフロントエンド実装

### ISSUE THREAD

**Issue by Syuparn** [project-inclusive/OpenFisca-Japan#89]
[Figma](https://www.figma.com/file/izSZUKF9r19BwkEnUZhHrM/%E3%83%9E%E3%82%A4%E5%88%B6%E5%BA%A6%E3%82%B7%E3%83%9F%E3%83%A5%E3%83%AC%E3%83%BC%E3%82%BF%E3%83%BC?type=design&node-id=0%3A1&mode=design&t=ArZGglM6HWTQMfIt-1)のフォーム画面・結果画面のGUIをもとに、重度心身障害者手当のフロントエンドを作ります。

https://github.com/project-inclusive/OpenFisca-Japan/issues/88 のバックエンド実装で新たに必要になった情報をフォームに追加します。
「給付されるお金」に「児童手当」と同様に「重度心身障害者手当」のプルダウンを作成します。
結果画面の説明に以下の文言を記載します。
「精神又は身体に重度の障害を持ち、常時複雑な介護を必要とする方に給付される手当」.
「詳細リンク」のリンク先は https://www.fukushi.metro.tokyo.lg.jp/shinsho/teate/juudo.html としてください。

**Comment by minosys-jp** [comment]
8/27 15:00 までに実施する修正。

- [ ] app_config.json への追加
- [ ] pageas/CalucationForms.tsx の useState() への追加
- [ ] forms/components/attributes/PrefectureMunicipality.tsx に東京都の場合のみ結果を出力指示するロジックを追加
- [ ] デバッグ

**Comment by SnoozingJellyfish** [comment]
PR #125 で対応のためクローズ
