### ISSUE TITLE
重度心身障害者手当の単体テストファイル作成

### ISSUE THREAD

**Issue by Syuparn** [project-inclusive/OpenFisca-Japan#90]
重度心身障害者手当の単体テストファイルを作成します。
`openfisca_japan/tests/東京都/福祉` 以下のyamlテストファイルに追記してください。
基本的に以下のポリシーで単体テストを行います。

- [x] 境界値テスト(障害者手帳、愛の手帳等級による受給有無)
- [x] 境界値テスト(所得制限による受給有無)

すでに記載している例が間違っているかもしれないので、その場合は修正いただけると助かります。

**Comment by Syuparn** [comment]
こちら着手したいと思います。

**Comment by SnoozingJellyfish** [comment]
PR #125 で対応のためクローズ
