### ISSUE TITLE
高等学校奨学給付金のフロントエンド実装

### ISSUE THREAD

**Issue by Syuparn** [project-inclusive/OpenFisca-Japan#92]
[Figma](https://www.figma.com/file/izSZUKF9r19BwkEnUZhHrM/%E3%83%9E%E3%82%A4%E5%88%B6%E5%BA%A6%E3%82%B7%E3%83%9F%E3%83%A5%E3%83%AC%E3%83%BC%E3%82%BF%E3%83%BC?type=design&node-id=0%3A1&mode=design&t=ArZGglM6HWTQMfIt-1)のフォーム画面・結果画面のGUIをもとに、高等学校奨学給付金のフロントエンドを作ります。

https://github.com/project-inclusive/OpenFisca-Japan/issues/91 のバックエンド実装で新たに必要になった情報をフォームに追加します。
「給付されるお金」に「児童手当」と同様に「高等学校奨学給付金」のプルダウンを作成します。
結果画面の説明に以下の文言を記載します。
「教材費、通学用品費等、高校で安心して教育を受けるために必要なお金の給付」.
「詳細リンク」のリンク先は https://www.kyoiku.metro.tokyo.lg.jp/admission/tuition/tuition/scholarship_public_school.html としてください。

(より良い文言が思いついた場合はそちらを使用していただいて構いません)

**Comment by Syuparn** [comment]
世帯員（子）に対して高校の種別（全日制・定時制、通信制、専攻科）を入力するフォームが必要になりそう

**Comment by SnoozingJellyfish** [comment]
PR #123 で対応済みのためクローズ
