### ISSUE TITLE
高等学校奨学給付金の単体テストファイル作成

### ISSUE THREAD

**Issue by Syuparn** [project-inclusive/OpenFisca-Japan#93]
高等学校奨学給付金の単体テストファイルを作成します。
openfisca_japan/tests/東京都/福祉/高等学校奨学給付金 以下のyamlテストファイルに追記してください。
https://www.kyoiku.metro.tokyo.lg.jp/admission/tuition/tuition/scholarship_public_school.html の表`支給される金額（年額）` をもとに、以下のケースの単体テストを行います。

高校の区分ごとに以下テストケース作成
- [x] 生活保護受給者
- [x] 所得の境界値テスト（非課税世帯か否か）
- [x] 子の人数

すでに記載している例が間違っているかもしれないので、その場合は修正いただけると助かります。

**Comment by he23inw3** [comment]
こちら着手します

**Comment by SnoozingJellyfish** [comment]
PR #123  で対応済みのためクローズ
