### ISSUE TITLE
質問リストのようなページを作成する

### ISSUE THREAD

**Issue by AZKZ** [project-inclusive/OpenFisca-Japan#94]
## 概要
- 社協や窓口でユーザーがどのような質問をすればよいかをサポートするためのページを作成する。

## 課題
- 計算結果の画面で社会福祉協議会の情報を載せているが、その場でどのような質問すればいいかなど具体的なアクションに関わる情報が表現できていない

## 参考
- [お悩みハンドブックの質問リスト](https://compass.graffer.jp/handbook/solutions/contact)

**Comment by SnoozingJellyfish** [comment]
#160 で完了のためクローズ。
dashboard/src/config/question_examples.json を編集すれば質問項目・文を変更可能。
