### ISSUE TITLE
配偶者特別控除の単体テスト追加

### ISSUE THREAD

**Issue by Syuparn** [project-inclusive/OpenFisca-Japan#96]
配偶者特別控除の単体テストファイルを作成します。
https://www.nta.go.jp/taxes/shiraberu/taxanswer/shotoku/1195.htm をもとに、`openfisca_japan/tests/所得/各種控除.yaml` の `TODO` となっている箇所に追記してください。
基本的に以下のポリシーで単体テストを行います。

- [x]  自分の所得区分前後の境界値テスト（配偶者の所得は固定）
- [x]  配偶者の所得区分前後の境界値テスト（自分の所得は固定）

すでに記載している例が間違っているかもしれないので、その場合は修正いただけると助かります。

**Comment by Syuparn** [comment]
こちら着手したいと思います。

**Comment by SnoozingJellyfish** [comment]
PR #110 で対応済みのためクローズします。
